#!/usr/bash

logwrite () {
  
        echo `date +"%m-%d-%Y %H:%M:%S - "` "$1"
        if [ ! $2 == "" ]
        then
                echo `date +"%m-%d-%Y %H:%M:%S - "`
        fi
}

function clientlock() {

  port=$1
  dbname=$2
  lock_id=$3
  pid=$4
  process_name=$5

  lock_action="LOCK";

  count=0;

#  echo "port=$port;dbname=$dbname;lock_action=$lock_action;lock_id=$lock_id;pid=$pid;process_name=$process_name";

  while [ $count -lt 120 ]
  do
    clientlock=`echo "select ps_clientlock('$lock_action','$lock_id',$pid,'$process_name')" | psql -p $port -q -At -d $dbname`;

    if [ $? -eq 0 ] && [ -n $clientlock ] && [ $clientlock == "locked" ]
    then
      return 0;
    else
      count=$((count + 1));
      sleep 1;
    fi
  done

  return 1;
}

function clientunlock() {

  port=$1
  dbname=$2
  lock_id=$3
  pid=$4
  process_name=$5

  lock_action="UNLOCK";

  count=0;

#  echo "port=$port;dbname=$dbname;lock_action=$lock_action;lock_id=$lock_id;pid=$pid;process_name=$process_name";

  while [ $count -lt 120 ]
  do
    clientlock=`echo "select ps_clientlock('$lock_action','$lock_id',$pid,'$process_name')" | psql -p $port -q -At -d $dbname`;
    if [ $? -eq 0 ] && [ -n $clientlock ] && [ $clientlock == "un-locked" ]
    then
      return 0;
    else
      count=$((count + 1));
      sleep 1;
    fi
  done

  return 1;
}
