.\"
.TH (cmd)params_get 3  22-Jan-2007  "DRMS MANPAGE" "DRMS Programmer's Manual"
.SH NAME
cmdparams_exists, cmdparams_getarg, cmdparams_get_str,
  cmdparams_isflagset, cmdparams_get_int, cmdparams_get_float,
  cmdparams_get_double, cmdparams_get_time, cmdparams_get_int8,
  cmdparams_get_int16, cmdparams_get_int32, cmdparams_get_int64,
  params_isflagset, params_get_str, params_get_char,
  params_get_short, params_get_int, params_get_float,
  params_get_double, params_get_time, params_get_int8,
  params_get_int16, params_get_int32, params_get_int64

get values in appropriate form from parsed command line and module
arguments list

.SH SYNOPSIS
.nf
.DT
.ft B
#include <cmdparams.h>
CmdParams_t *parms;
char *name;
int status;

int cmdparams_exists (parms, name);
char *cmdparams_getarg (parms, int num);
int cmdparams_numargs (parms);
int cmdparams_isflagset (parms, name);
char *cmdparams_get_str (parms, name, &status);
int cmdparams_get_int (parms, name, &status);
float cmdparams_get_float (parms, name, &status);
double cmdparams_get_double (parms, name, &status);
double cmdparams_get_time (parms, name, &status);
int8_t cmdparams_get_int8 (parms, name, &status);
int16_t cmdparams_get_int16 (parms, name, &status);
int32_t cmdparams_get_int32 (parms, name, &status);
int64_t cmdparams_get_int64 (parms, name, &status);
int params_isflagset (parms, name);
char *params_get_str (parms, name);
char params_get_char (parms, name);
short params_get_short (parms, name);
int params_get_int (parms, name);
float params_get_float (parms, name);
double params_get_double (parms, name);
double params_get_time (parms, name);
int8_t params_get_int8 (parms, name);
int16_t params_get_int16 (parms, name);
int32_t params_get_int32 (parms, name);
int64_t params_get_int64 (parms, name);

.SH DESCRIPTION

These functions return values of the appropriate type from the hash list
of parameters expected to be available to a module as a global variable.

.I cmdparams_get_XXX
where \fIXXX\fR is not \fIstr\fR or \fItime\fR returns the value in the
parameters list associated with the specified name. If there is no entry
with that name or if the type does not correspond to \fIXXX\fR,
then the value representing missing (fill) data for that type is returned,
and the \fIstatus\fR value is set to a non-zero code.
\fIcmdparams_get_str()\fR returns a pointer to the associated string,
and \fIcmdparams_get_time()\fR returns a double representing the internal
time representation of a parsed date-time string.

.I params_get_XXX
are equivalent functions, but without the third argument for a status value.

.SH RETURN VALUES
\fIcmdparams_isflagset() \fR and \fIparams_isflagset()\fR return the value 0
if either the corresponding parameter is 0 or does not exist; otherwise it
returns the integer value associated with the parameter (normally -1 if the
argument is of type ARG_FLAG).

On a failure, such as inability to locate the named key or to successfully
parse the associated value string according to the prescribed datatype,
\fI[cmd]params_get_str\fR returns a NULL pointer; all others return the
MISSING value defined for the type.

.SH BUGS
If \fIcmdparams_get_str()\fR (which is called by all the other versions of
\fIcmdparams_get_XXX()\fR)cannot find a hash table entry for the requested
name, it will use the corresponding environment variable, if it exists.

.SH "SEE ALSO"
.B module(1)
.B cmdparams_parse(3)
.R <cmdparams_set(3)>
.R <DRMS_missing(5)>
