#ifndef _DRMS_STATUSCODES_H
#define _DRMS_STATUSCODES_H


/* DRMS error codes. */
#define DRMS_NO_ERROR                   0
#define DRMS_SUCCESS                    0
#define DRMS_ERROR_BADSEQUENCE      10001
#define DRMS_ERROR_BADTEMPLATE      10002
#define DRMS_ERROR_UNKNOWNSERIES    10003
#define DRMS_ERROR_UNKNOWNRECORD    10004
#define DRMS_ERROR_UNKNOWNLINK      10005
#define DRMS_ERROR_UNKNOWNKEYWORD   10006
#define DRMS_ERROR_UNKNOWNSEGMENT   10007
#define DRMS_ERROR_BADFIELDCOUNT    10008 
#define DRMS_ERROR_INVALIDLINKTYPE  10009
#define DRMS_ERROR_BADLINK          10010
#define DRMS_ERROR_UNKNOWNUNIT      10011
#define DRMS_ERROR_QUERYFAILED      10012
#define DRMS_ERROR_BADQUERYRESULT   10013
#define DRMS_ERROR_UNKNOWNSU        10014
#define DRMS_ERROR_INVALIDACTION    10015
#define DRMS_ERROR_COMMITREADONLY   10016
#define DRMS_ERROR_NULLARGUMENT     10017
#define DRMS_ERROR_BADRECORDCOUNT   10018
#endif


