create type drmssession as (
     sessionid           bigint,
     hostname            text, 
     port                int8, 
     pid                 int8, 
     sunum               bigint, 
     sudir               text, 
     username            text, 
     starttime           text, 
     lastcontact         text, 
     endtime             text, 
     clients             int8, 
     status              text, 
     sums_thread_status  text, 
     jsoc_version        text );
