#!/usr/bin/perl
#/home/production/cvs/JSOC/base/sums/scripts/sum_start_n02_jim
#This is to start the sum_svc and related servers on n02.
#Call with -M will not send mail notification.
#Call with -f to force a stop if needed.
#
$| = 1;                 #flush output as we go
$ENV{'SUMSERVER'} = "n02";      #make sure we stay in this machine
#$DB = "jsoc_sums";	#the "real" db that production uses for sums
$DB = "jim";	#the "real" db that production uses for sums
$DBDRMS = "jsoc_sums";	#the db use for drms (used by sum_pe_svc)
$GREPPS = "388";	#grep for this in ps -ef
#$GREPPS = "jim";
$HOST = "n02.Stanford.EDU"; #where sum_svc runs

$user = $ENV{'USER'};
if($user ne "production") {
  print "You must be user production to run\n";
  exit;
}
$host = `hostname`;
chomp($host);
if($host ne $HOST) {
  print "This can only be run on $HOST.\n";
  exit;
}
$mailflg = 1;
$forceflg = 0;
$forcearg = "";
while ($ARGV[0] =~ /^-/) {
  $_ = shift;
  if (/^-M(.*)/) {
    $mailflg = 0;
  }
  elsif(/^-f(.*)/) {
    $forceflg = 1;
    $forcearg = "-f";
  }
  else {
    print "Illegal switch\n";
    exit;
  }
}

$PID = getppid;
$MLOGFILE = "/tmp/sum_start_mail_n02_jim.$PID";
$LOGFILE = "/tmp/sum_start_n02_jim.$PID";
open(LOG, ">$LOGFILE") || die "Can't open $LOGFILE: $!\n";
open(MLOG, ">$MLOGFILE") || die "Can't open $MLOGFILE: $!\n";
($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time);
$sec2 = sprintf("%02d", $sec);
$min2 = sprintf("%02d", $min);
$hour2 = sprintf("%02d", $hour);
$mday2 = sprintf("%02d", $mday);
$mon2 = sprintf("%02d", $mon+1);
$year2 = sprintf("%02d", $year);
$date = (1900 + $year).".".$mon2.".$mday2"._.$hour2.":$min2".":$sec2";
print "sum_start_n02_jim at $date\n\n";
print LOG "sum_start_n02_jim at $date\n\n";
print MLOG "sum_start_n02_jim at $date\n";
print MLOG "See $LOGFILE for more details\n";

@ps_prod = `ps -ef | grep $GREPPS`;
#print "The ps -ef for producttion is:\n@ps_prod\n";
print LOG "The ps -ef for product is:\n@ps_prod\n";
while($_ = shift(@ps_prod)) {
  if(/^$GREPPS/) {	#do for all production processes
    if(/sum_start_n02_jim/) {	#don't kill ourselves
      next;
    }
    if(/sum_svc $DB/ || /sum_svc -o $DB/) {
      ($a, $psid, $c) = split(/\s+/, $_);
      $process = "sum_svc";
    }
    elsif(/tape_svc $DB/ || /tape_svc -o $DB/) {
      ($a, $psid, $c) = split(/\s+/, $_);
      $process = "tape_svc";
    }
    elsif(/drive0_svc $DB/) {
      ($a, $psid, $c) = split(/\s+/, $_);
      $process = "drive0_svc";
    }
    elsif(/drive1_svc $DB/) {
      ($a, $psid, $c) = split(/\s+/, $_);
      $process = "drive1_svc";
    }
    elsif(/drive2_svc $DB/) {
      ($a, $psid, $c) = split(/\s+/, $_);
      $process = "drive2_svc";
    }
    elsif(/drive3_svc $DB/) {
      ($a, $psid, $c) = split(/\s+/, $_);
      $process = "drive3_svc";
    }
    elsif(/robot0_svc $DB/) {
      ($a, $psid, $c) = split(/\s+/, $_);
      $process = "robot0_svc";
    }
    elsif(/sum_rm $DB/) {
      ($a, $psid, $c) = split(/\s+/, $_);
      $process = "sum_rm";
    }
    elsif(/sum_pe_svc $DBDRMS/) {
      ($a, $psid, $c) = split(/\s+/, $_);
      $process = "sum_pe_svc";
    }
    elsif(/ sumck/) {
      if($sumck) {
        ($a, $psid, $c) = split(/\s+/, $_);
        $process = "sumck";
      }
    }
    else {
      next;
    }
    print "** NOTE: \"$process $DB\" still running\n";
    print LOG "** NOTE: \"$process $DB\" still running\n";
      print "Do you want me to do a sum_stop_n02_jim followed by a sum_start_n02_jim (y or n):\n";
      while(<STDIN>) {
        chop($_);
        if(($_ eq "Y") || ($_ eq "y")) { 
          last;
        }
        else { 
          print "Aborting sum_start_n02_jim\n";
          exit;
        }
      }
        if($mailflg) {
          $cmd = "sum_stop_n02_jim $forcearg";
        }
        else {
          $cmd = "sum_stop_n02_jim -M $forcearg";
        }
        if(system($cmd)) {
          print "Error: failure on sum_stop_n02_jim\n";
          exit;
        }
        #make sure nothing left running
        @ps_prod = `ps -ef | grep $GREPPS`;
        while($_ = shift(@ps_prod)) {
          if(/^$GREPPS/) {	#do for all production processes
            if(/sum_svc $DB/ || /sum_svc -o $DB/) {
              print "Error: sum_svc $DB still running after sum_stop?\n";
              exit;
            }
            elsif(/tape_svc $DB/ || /tape_svc -o $DB/) {
              print "Error: tape_svc $DB still running after sum_stop?\n";
              exit;
            }
            elsif(/drive0_svc $DB/) {
              print "Error: drive0_svc $DB still running after sum_stop?\n";
              exit;
            }
            elsif(/drive1_svc $DB/) {
              print "Error: drive1_svc $DB still running after sum_stop?\n";
              exit;
            }
            elsif(/drive2_svc $DB/) {
              print "Error: drive2_svc $DB still running after sum_stop?\n";
              exit;
            }
            elsif(/drive3_svc $DB/) {
              print "Error: drive3_svc $DB still running after sum_stop?\n";
              exit;
            }
            elsif(/robot0_svc $DB/) {
              print "Error: robot0_svc $DB still running after sum_stop?\n";
              exit;
            }
            elsif(/sum_rm $DB/) {
              print "Error: sum_rm $DB still running after sum_stop?\n";
              exit;
            }
            elsif(/sum_pe_svc $DBDRMS/) {
              print "Error: sum_pe_svc $DBDRMS still running after sum_stop?\n";
              exit;
            }
            else {
              next;
            }
          }
        }
  }
}
    `/bin/rm -f /usr/local/logs/SUM/RESTART_AFTER_REBOOT`;
    print "Is this sum_start following a n02 reboot?\n";
    print "If you answer 'y' all the T950 tapes in drives will be unloaded\n";
    print "Starting after a reboot? (y or n): ";
    while(<STDIN>) {
      chop($_);
      if(($_ eq "Y") || ($_ eq "y")) {
        `touch /usr/local/logs/SUM/RESTART_AFTER_REBOOT`;
      }
      last;
    }

        print "** Now starting: sum_svc $DB\n";
        print LOG "** Now starting: sum_svc $DB\n";
        $cmd = "sum_pe_svc $DBDRMS &";
#        if(system($cmd)) {
#          print "Error: failure on sum_pe_svc $DBDRMS\n";
#        }
        $cmd = "sum_svc $DB &";
        if(system($cmd)) {
          print "Error: failure on sum_svc $DB\n";
        }
        $cmd = "sumck_n02_jim &";
        if(system($cmd)) {
          print "Error: failure on sumck_n02\n";
        }
        print "SUM n02 Start Complete\n";
        print LOG "SUM n02 Start Complete\n";
        close(LOG);
        close(MLOG);
        $mail = "Mail -s \"SUM n02 Start Complete\"";
        #$to = "sssc_crew\@solar2";
        $to = "jim";
        $cmd = "$mail $to < $MLOGFILE";
        if($mailflg) { system $cmd; }
        exit;

