
.\"
.TH show_series 1  23-July-2006  "DRMS MANPAGE" "DRMS Programmer's Manual"
.SH NAME
show_series \- DRMS List DataSeries names with optional information
.SH SYNOPSIS
.nf
.B show_series {filter} {-p} {-v}

.SH DESCRIPTION
Show_series lists JSOC dataseries.  It can optionally show the prime keywords and
description.  The list can be filtered by specifying a grep-like regular expression.
The flags that control show_keys are:
.PP
.B -p
Show the Prime Keys and Description
.br
.B -h
Print usage message and exit
.br
.B -v
Verbose - noisy.
.br
.B <filter>
A pattern using grep-like rules to select the series to list.
.br
.PP
.SH "SEE ALSO"
.BR show_keys(1)
.BR describe_series(1)
