A(simple, kRKW_simple, NULL)
A(extend, kRKW_extend, NULL)
A(bzero, kRKW_bzero, NULL)
A(bscale, kRKW_bscale, NULL)
A(blank, kRKW_blank, NULL)
A(bitpix, kRKW_bitpix, NULL)
A(naxis, kRKW_naxis, NULL)
A(comment, kRKW_comment, CommHndlr)
A(history, kRKW_history, CommHndlr)
A(end, kRKW_end, NULL)
A(date, kRKW_date, DateHndlr)
A(date__obs, kRKW_date__obs, DateHndlr)
A(primekeystring, kRKW_primekeystring, NULL)
A(crpix, kRWK_cripx, WCSHandler)
A(crval, kRWK_crval, WCSHandler)
A(cdelt, kRWK_cdelt, WCSHandler)
A(crota, kRWK_crota, WCSHandler)
A(crder, kRWK_crder, WCSHandler)
A(csyer, kRWK_csyer, WCSHandler)
B(bitpix, kFKW_bitpix)
B(naxis, kFKW_naxis)
B(simple, kFKW_simple)
B(extend, kFKW_extend)
B(blank, kFKW_blank)
B(bzero, kFKW_bzero)
B(bscale, kFKW_bscale)
B(end, kFKW_end)
