#!/bin/bash

# Environment variables are exported by slony.env

slonik <<_EOF_

cluster name = $CLUSTERNAME;

node 1 admin conninfo = 'dbname=$MASTERDBNAME host=$MASTERHOST port=$MASTERPORT user=$REPUSER';
node 2 admin conninfo = 'dbname=$SLAVEDBNAME host=$SLAVEHOST port=$SLAVEPORT user=$REPUSER';

set drop table ( id = $tabid, origin = 1);

_EOF_

# $tabid is the ID that is associated with the table that you wish to unpublish.
# select * from _jsoc.sl_table;
# returns:
# tab_id | tab_reloid |    tab_relname     | tab_nspname | tab_set |       tab_idxname       | tab_altered |        tab_comment
# --------+------------+--------------------+-------------+---------+-------------------------+-------------+---------------------------
#    16 |     629454 | test4              | su_arta     |       1 | test4_pkey              | t           | su_arta.test4

# the ID that you assign to $tabid in the script is the id in the column "tab_id" (16 in this example)
